package com.ivanova;

public enum ColumnHeaders {
    DAY_OF_MONTH,
    DAY_OF_WEEK,
    FLIGHT_DATE,
    UNIQUE_CARRIER,
    TAIL_NUM,
    ORIGIN_AIRPORT_ID,
    ORIGIN,
    ORIGIN_STATE_NAME,
    DEST_AIRPORT_ID,
    DEST,
    DEST_STATE_NAME,
    DEP_TIME,
    DEP_DELAY,
    WHEELS_OFF,
    WHEELS_ON,
    ARR_TIME,
    ARR_DELAY,
    CANCELLED,
    CANCELLATION_CODE,
    DIVERTED,
    AIR_TIME,
    DISTANCE


}
